"""Add last_extracted_at to attachments

Revision ID: 908e456afafd
Revises: add_document_classification
Create Date: 2025-06-16 10:41:16.145213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908e456afafd'
down_revision = 'add_document_classification'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('last_extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'last_extracted_at')
    # ### end Alembic commands ###